# SPDX-License-Identifier: GPL-2.0+
#
# SoC-specific ST7789V support (optional).
# When adding e.g. sunxi.c, use: obj-$(CONFIG_VIDEO_ST7789V_SUNXI) += sunxi.o
obj-$(CONFIG_VIDEO_ST7789V_SUNXI_H3) += sunxi_h3.o
